services:
  # -----------------------
  # Cameras (fire frames)
  # -----------------------
  camera_area01: &camera_template
    build: ./camera
    environment:
      AREA: "area01"
      FRAMES_DIR: "/app/frames_cam01"
      FPS: "0.5"
      NATS_URL: "nats://98.95.255.36:4222"
    restart: unless-stopped

  camera_area02: { <<: *camera_template, environment: { AREA: "area02", FRAMES_DIR: "/app/frames_cam01", FPS: "0.5", NATS_URL: "nats://98.95.255.36:4222" } }

  # -----------------------
  # Alarm radios (tracing)
  # -----------------------
  alarm_area01: &alarm_template
    build: ./alarm
    environment:
      AREA: "area01"
      NATS_URL: "nats://98.95.255.36:4222"
    restart: unless-stopped

  alarm_area02: { <<: *alarm_template, environment: { AREA: "area02", NATS_URL: "nats://98.95.255.36:4222" } }
